version: '3.9'

services:
  db:
    image: postgres:15
    container_name: united-fc-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: united-fc
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: united-fc-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  maildev:
    image: maildev/maildev:latest
    container_name: united-fc-maildev
    restart: always
    ports:
      - '1081:1081' # Web UI
      - '1026:1026' # SMTP server
    environment:
      - MAILDEV_SMTP_PORT=1026
      - MAILDEV_WEB_PORT=1081

volumes:
  postgres_data:
  redis_data:
