name: CI/CD Deploy to GCP

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  WEB_IMAGE: ${{ secrets.GCP_WEB_IMAGE }}
  API_IMAGE: ${{ secrets.GCP_API_IMAGE }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: footdash

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Confirm secret exists
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "❌ GCP_SA_KEY is NOT set"
            exit 1
          else
            echo "✅ GCP_SA_KEY is set"
          fi

      # 3. Authenticate with GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 4. Configure Docker to push to GCP
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev

      - name: Build & Push Web Client Docker
        run: |
          docker build \
            -f apps/web-client/Dockerfile \
            --build-arg API_URL=${{ secrets.API_URL }} \
            -t $WEB_IMAGE:latest .
          docker push $WEB_IMAGE:latest

      # 6. Build & Push API Docker
      - name: Build & Push API Docker
        working-directory: . # root of Turbo repo
        run: |
          docker build -t $API_IMAGE:latest -f Dockerfile.api .
          docker push $API_IMAGE:latest
